swagger: '2.0'
info:
  version: 1.0.0
  title: Travel Time
  contact:
    name: Nicolas Schmitt
    email: nicontoso@outlook.com
paths:
  /api/travel:
    get:
      summary: Travel Time
      description: |
        Gets available routes and travel time
      parameters:
        - name: from
          in: query
          description: departure
          required: true
          type: string
          format: 'latitude,longitude'
        - name: to
          in: query
          description: arrival
          required: true
          type: string
          format: 'latitude,longitude'
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayOfRoutes
            type: array
            items:
              title: Route
              type: object
              properties:
                name:
                  type: string
                time:
                  type: number
                dist:
                  type: number
